auto: true
server: true
pygments: true
permalink: /:categories/:year/:month/:day/:hour/:title/
root_dir: "http://behlbor.github.com/chirikova2012"
baseurl: "http://behlbor.github.com/chirikova2012"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata:
    _posts/news: |
      published: true
      layout: news
      descr: Short summary of your article.
      author_twitter: @chirikova
      author: Evgenia Chirikova
      image:
      categories:
      - news