auto: true
server: true
pygments: true
permalink: none
root_dir: "chirikova2012"
baseurl: "http://behlbor.github.com/chirikova2012"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md