auto: true
server: true
pygments: true
permalink: /:categories/:year/:month/:day/:title/
root_dir: "http://echirikova.ru"
baseurl: "http://echirikova.ru"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md

markdown: rdiscount
pygments: true
lsi: true
exclude: ['README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile']
production: false
//add this line to add pagination
paginate: 10 //the number of post per page

prose:
  rooturl: "_posts"
  metadata:
    _posts/news: |
      published: true
      layout: news
      title: Your Post Title
      descr: Short summary of your news
      time: Local time, e.g. 18:30
      tag: none
      categories:
      - news
    _posts/video: |
      published: true
      layout: video
      title: Your Post Title
      descr: Short summary of your news
      time: Local time, e.g. 18:30
      categories:
      - video